<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-06-26 13:48
=======
# Generated by Django 3.0.7 on 2020-06-26 13:49
>>>>>>> b7c6480b921cd4202db080e1fc205c1399bbcdd1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1200)),
                ('issued', models.CharField(max_length=1200)),
            ],
        ),
    ]
