# Generated by Django 3.0.7 on 2020-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issued',
            field=models.CharField(max_length=100),
        ),
    ]
